### ISSUE TITLE
getauthentication not executed?

### ISSUE THREAD

**Issue by dineshbvadhia** [lucasdavid/wikiart#17]
My tests show the getauthentication function in fetcher.py doesn't get executed.

**Comment by dineshbvadhia** [comment]
console.py doesn't call the getauthentication() function in fetcher.py. Is there a reason for this?

**Comment by dineshbvadhia** [comment]
Closing Issue as no longer a problem.

**Comment by lucasdavid** [comment]
So It seems api/2 requires an authentication token to extract the metadata. The `getauthentication` util was put there in order to facilitate development towards that front, but this repo still works using the open (free of auth) v1 and we haven't updated yet. 

An external collaborator has adapted the code to access the api v2, but I'm still trying to find some time to review the code...
